site_name: NetBox Toolkit Plugin
site_description: NetBox plugin for running commands on network devices using Scrapli
site_author: NetBox Toolkit Contributors
site_url: https://bonzo81.github.io/netbox-toolkit-plugin/

# Repository
repo_name: netbox-toolkit-plugin
repo_url: https://github.com/bonzo81/netbox-toolkit-plugin
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 NetBox Toolkit Contributors

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
#    - navigation.instant
    - navigation.tracking
#    - navigation.sections
#    - navigation.expand
    - navigation.prune      # Collapses inactive sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.copy
    - content.code.annotate
#    - toc.integrate         # DISABLED: This was causing the left sidebar to expand with page TOC
  icon:
    edit: material/pencil

# Plugins
plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - footnotes
  - abbr
  - def_list

# Page tree
nav:
  - Start Here:
      - README.md
      - Platform Support: platform-support.md
      - GUI vs API Comparison: user/gui-vs-api.md
  - User Documentation:
      - Setup Guides:
          - Plugin Installation: user/plugin-installation.md
          - Plugin Upgrade: user/plugin-upgrade.md
          - Plugin Configuration: user/plugin-configuration.md
          - Permissions Creation: user/permissions-creation.md
          - Command Creation: user/command-creation.md
          - Device Credentials: user/device-credentials.md
          - Logging Guide: user/logging.md
  - API Documentation:
      - Overview:
          - api/index.md
          - Commands API: api/commands.md
          - Command Logs API: api/command-logs.md
          - Authentication & Permissions: api/auth.md
          - API Endpoint Reference: api/endpoint-reference.md
          - Error Handling: api/errors.md
  - Examples:
          - Permission Examples: user/permission-examples.md
          - API Examples: api/workflows.md
          - API Automation Examples: api/automation-examples.md

  - Development:
      - Start Here:
          - development/index.md
          - Setup: development/setup.md
      - Contributing:
          - Contribution Types: development/contribution-types.md
          - Development Workflow: development/development-workflow.md
          - Technical Stack: development/technical-stack.md
          - Getting Help: development/getting-help.md
      - Reference:
          - Code Guide: development/code-guide.md
          - Architecture: development/architecture.md
          - Module Structure: development/module-structure.md
  - Changelog:
      - Changelog: changelog.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bonzo81/netbox-toolkit-plugin
  version:
    provider: mike

# Watch extra files
watch:
  - netbox_toolkit_plugin/
