# Generated by Django 5.2.7 on 2025-10-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_toolkit_plugin', '0014_add_encrypted_token_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='notes',
            field=models.TextField(blank=True, help_text="Optional notes or comments about this command execution (e.g., 'pre-change OSPF config')"),
        ),
        migrations.AlterField(
            model_name='devicecredentialset',
            name='access_token',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
